name: Tests

on:
    pull_request:

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install node v20
      uses: actions/setup-node@v1
      with: 
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Run Tests
      run: npm run test
      